name: soccer_sub
channels:
  - conda-forge
dependencies:
  - black
  - ipywidgets
  - isort
  - jax
  - jupyter
  - jupyterlab
  - matplotlib
  - nbqa
  - numba
  - numpy
  - numpyro
  - nutpie
  - pandas
  - pip
  - pre-commit
  - preliz
  - pymc
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - ruff
  - watermark
  - pip:
    - -e .
